# Each new term in the Fibonacci sequence is generated by adding the previous two terms
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By Considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def fibonacci_sum_even(n):
    a, b = 0, 1
    sum = 0
    while b < n:
        if b % 2 == 0:
            sum += b
        a, b = b, a + b
    return sum

fibonacci_sum_even(4000000)
# 4613732